import fs from 'fs';
import path from 'path';

// Apps built with the iOS 27.1 SDK must adopt the UIScene life cycle, or they fail at launch with
// "UIScene life cycle is required for apps built with this SDK". Expo SDK 57 ships
// ExpoAppSceneDelegate for this, but its app template does not use it yet.

export type SceneLifecycleResult =
  | { status: 'adopted'; contents: string }
  | { status: 'already-adopted' }
  | { status: 'unrecognized'; missing: string };

const APP_DELEGATE_DECLARATION = 'class AppDelegate: ExpoAppDelegate {';

// The template creates the window itself; under the scene life cycle, the scene delegate does.
const WINDOW_SETUP = `#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif
`;

const SCENE_DELEGATE = `
// @generated by expo-foldables: adopts the UIScene life cycle required by the iOS 27.1 SDK.
class SceneDelegate: ExpoAppSceneDelegate {}
`;

/** Rewrites an Expo SDK 57 template AppDelegate.swift to use ExpoAppSceneDelegate. */
export function adoptSceneLifecycle(appDelegate: string): SceneLifecycleResult {
  if (
    /\bExpoAppSceneDelegate\b|\bUIWindowSceneDelegate\b|class SceneDelegate\b/.test(appDelegate)
  ) {
    return { status: 'already-adopted' };
  }
  for (const expected of [APP_DELEGATE_DECLARATION, WINDOW_SETUP]) {
    if (!appDelegate.includes(expected)) {
      return { status: 'unrecognized', missing: expected };
    }
  }
  const contents =
    appDelegate
      .replace(
        APP_DELEGATE_DECLARATION,
        'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {'
      )
      .replace(WINDOW_SETUP, '') + SCENE_DELEGATE;
  return { status: 'adopted', contents };
}

export type InfoPlist = Record<string, unknown>;

/** Declares SceneDelegate as the app's window scene delegate, unless a scene manifest exists. */
export function addSceneManifest(infoPlist: InfoPlist): InfoPlist {
  if (infoPlist.UIApplicationSceneManifest !== undefined) {
    return infoPlist;
  }
  return {
    ...infoPlist,
    UIApplicationSceneManifest: {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    },
  };
}

/** Whether the installed `expo` package ships ExpoAppSceneDelegate (Expo SDK 57 and later). */
export function isSceneDelegateAvailable(projectRoot: string): boolean {
  try {
    const expoPackageJson = require.resolve('expo/package.json', { paths: [projectRoot] });
    const delegate = path.join(
      path.dirname(expoPackageJson),
      'ios',
      'AppDelegates',
      'ExpoAppSceneDelegate.swift'
    );
    return fs.existsSync(delegate);
  } catch {
    return false;
  }
}
